### ISSUE TITLE
Saliency output format

### ISSUE THREAD

**Issue by mortonjt** [flatironinstitute/DeepFRI#1]
I'm noticing that there are pickle files that are the output of deepfri.

There are a few immediate reasons why this may not be advantageous

1. Pickle files are specific for python - can't parse them in another language
2. There are security issues surrounding python
3. There are likely to be version issues that pop up due to the choice of python and numpy, where one user has numpy=1.10, but the pickle can only be read in 1.17 (these issues do actually happen).

Looking inside of the contents, it looks like this can be easily encoded as a json format, which is a more forgiving format.

**Comment by VGligorijevic** [comment]
Thank you @mortonjt ! DeepFRI now outputs files in json format.

**Comment by mortonjt** [comment]
Awesome!!
