### ISSUE TITLE
Cannot get your data

### ISSUE THREAD

**Issue by Yechonghang** [flatironinstitute/DeepFRI#23]
The link of the bc-95.out is not available,which is https://cdn.rcsb.org/resources/sequence/clusters/bc-95.out
Can you update it so that we can enjoy it again, thanks!

**Comment by anar-rzayev** [comment]
You can use the Wayback machine to see the previous snapshots of this page. I attach the link, hope it helps!
http://web.archive.org/web/20220202030208/https://cdn.rcsb.org/resources/sequence/clusters/bc-95.out

**Comment by Yechonghang** [comment]
> You can use the Wayback machine to see the previous snapshots of this page. I attach the link, hope it helps! http://web.archive.org/web/20220202030208/https://cdn.rcsb.org/resources/sequence/clusters/bc-95.out

Thank you！

**Comment by song2000012138** [comment]
> You can use the Wayback machine to see the previous snapshots of this page. I attach the link, hope it helps! http://web.archive.org/web/20220202030208/https://cdn.rcsb.org/resources/sequence/clusters/bc-95.out
From what time should i download
