### ISSUE TITLE
URLs for data and models are not available

### ISSUE THREAD

**Issue by alexgcsa** [flatironinstitute/DeepFRI#32]
Hello, 

the URLs provided for data and pretrained models on github are not available. With all I have an error message "403 Forbidden". Would it be possible to update them again? 

Following, the list of unavailable URLs:

### **Data**
**PDB Gene Ontology (19GB)**
https://users.flatironinstitute.org/vgligorijevic/public_www/DeepFRI_data/PDB-GO.tar.gz

**PDB Enzyme Commission (13GB)**
https://users.flatironinstitute.org/vgligorijevic/public_www/DeepFRI_data/PDB-EC.tar.gz

**SWISS-MODEL Gene Ontology (165GB)**
https://users.flatironinstitute.org/vgligorijevic/public_www/DeepFRI_data/SWISS-MODEL-GO.tar.gz

**PDB Enzyme Commission (117GB)**
https://users.flatironinstitute.org/vgligorijevic/public_www/DeepFRI_data/SWISS-MODEL-EC.tar.gz

### **Pretrained models**
**Models (use these models if you run DeepFRI on GPU)**
https://users.flatironinstitute.org/vgligorijevic/public_www/DeepFRI_data/trained_models.tar.gz

**Newest Models (use these models if you run DeepFRI on CPU)**
https://users.flatironinstitute.org/vgligorijevic/public_www/DeepFRI_data/newest_trained_models.tar.gz

Thank you very much!

Cheers,

Alex

**Comment by dougrenfrew** [comment]
Thanks for bringing this to our attention. We'll get the files hosted somewhere else and update the links. I'll post again here when it is complete.

**Comment by dougrenfrew** [comment]
The links became inactive in error. The `README.md` has been updated with functioning links.

**Comment by alexgcsa** [comment]
Thank you!

Cheers,

Alex
