### ISSUE TITLE
Installation failure

### ISSUE THREAD

**Issue by lalalagartija** [flatironinstitute/DeepFRI#43]
Hi, 
I have tried many ways to install deepFRI,all have failed. 
First I created a conda environment to have python3.7. Then I installed everything with pip. 
I get `Illegal instruction` when running `python predict.py -h `
and 
`python -m pip show tensorflow`
`WARNING: Package(s) not found: tensorflow`

Then I installed tensorflow v2.9.3
and the error was : 
`python predict.py -h`
`The TensorFlow library was compiled to use AVX instructions, but these aren't available on your machine.
Aborted`

I tried instead tensorflow v1.15.3 or v 2.5 and the error is back to
 `Illegal instruction`

I instead tried making a python environment with python 3.9 and I get similar errors. 
Can you please provide with all the packages in an environment that worked for you and in particular, an appropriate version of tensorflow ?

**Comment by lalalagartija** [comment]
The issue was resolved as I found I machine with a GPU to install it on.

**Comment by Rohit-Satyam** [comment]
This also works!!

```
mamba create -n deepfri2 python=3.7 tensorflow biopython numpy tqdm scikit-learn
mamba activate deepfri2
```
and then

```
pip install .
```
