### ISSUE TITLE
Text version of SWISS-MODEL dataset

### ISSUE THREAD

**Issue by bl-2633** [flatironinstitute/DeepFRI#6]
Hi, Can you release the text version of the SWISS-MODEL dataset like the PDB dataset included in the repository? Thanks!

**Comment by VGligorijevic** [comment]
Text version of the SWISS-MODEL dataset is now in the repository.

**Comment by bcaldir** [comment]
Hey, it seems like you've only added the train and valid sets to the repo. Would you add the test data as well?

**Comment by VGligorijevic** [comment]
The testa data is only composed of PDB file and you find it here: `https://github.com/flatironinstitute/DeepFRI/tree/master/preprocessing/data/`
In the comparison to other methods we only used experimental crystal structures from PDB.
